# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2500)),
                ('emily', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emily.Set'),
        ),
    ]
